# Generated by Django 5.0 on 2024-02-26 17:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_customuser_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 26, 17, 56, 54, 676202, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 26, 17, 56, 54, 676311, tzinfo=datetime.timezone.utc)),
        ),
    ]
