# Generated by Django 5.0 on 2024-02-27 03:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_customuser_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 27, 3, 38, 4, 713657, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 27, 3, 38, 4, 713730, tzinfo=datetime.timezone.utc)),
        ),
    ]
